### ISSUE TITLE
searching a module, and erlang.mk ?

### ISSUE THREAD

**Issue by crownedgrouse** [wb14123/erlang_module#1]
Hi,
your top 1000 Erlang module is nice , but how to find a module in almost 40 pages ?
A minimal search widget would be a minimum MHO.
And by reading your blog, looks like only projects using rebar.config is listed.
What about those with erlang.mk ? 
regards

**Comment by crownedgrouse** [comment]
Note, you can fetch dependencies in the Makefile including erlang.mk, by getting DEPS . More info at https://github.com/ninenines/erlang.mk#packages .

**Comment by wb14123** [comment]
Hi, thanks for comment.

I'd like to add the support of `erlang.mk`. The search is not so necessary for me, since the projects after 10 pages will only have 1 or 2 projects depend on it. They are not so popular.

**Comment by crownedgrouse** [comment]
I did some contributions to erlang.mk , I can help, maybe , on how to do that.

for the search, it is necessary, i think, for two purposes :
- find the rank of it s own project.
- find projects needed as dependency by searching in the description some key words.

**Comment by wb14123** [comment]
I'd like to know, if I specify a package, for example:

```
DEPS = cowboy
```

Where does it find the package `cowboy`? Do I must specify it like this?

```
dep_cowboy = git https://github.com/ninenines/cowboy
```

**Comment by crownedgrouse** [comment]
no, there is an official index.
you should download first a file called packages.v2.tsv  (or something like that) on erlang.mk repo.

« Envoyé depuis mon mobile » Eric

Bin Wang notifications@github.com a écrit :

**Comment by crownedgrouse** [comment]
dep_xxxxx is used when a package is not available in the index, or a specific version should be used.

« Envoyé depuis mon mobile » Eric

Bin Wang notifications@github.com a écrit :

**Comment by crownedgrouse** [comment]
at root of ninenines/erlang.mk project on github.

« Envoyé depuis mon mobile » Eric

Bin Wang notifications@github.com a écrit :

**Comment by crownedgrouse** [comment]
https://github.com/ninenines/erlang.mk/blob/master/packages.v2.tsv

« Envoyé depuis mon mobile » Eric

Bin Wang notifications@github.com a écrit :

**Comment by wb14123** [comment]
Thanks. I've found that.

**Comment by wb14123** [comment]
I've add erlang.mk support in commit a26b6356f62e4 . If you'd like to add search, open a new issue please.

**Comment by crownedgrouse** [comment]
is the web site updated and using this commit ? not easy to detect if erlang.mk are in it...

**Comment by wb14123** [comment]
Yes, it already updated. Just a little of them use erlang.mk.

**Comment by crownedgrouse** [comment]
thanks,
I did not thought to this before, but this would have been nice to show this for each module... some want only rebar or erlang.mk modules as dependencies...
a tag, or a color code ?

« Envoyé depuis mon mobile » Eric
