### ISSUE TITLE
searching modules

### ISSUE THREAD

**Issue by crownedgrouse** [wb14123/erlang_module#2]
A searching field would be nice to add to web site in order to : 
- find its own module rank
- find if  modules exist on something, and use the most popular.

**Comment by crownedgrouse** [comment]
BTW, any update on this ;>)  ???

**Comment by wb14123** [comment]
No. It just works. So I think it is some problem on Heroku.

**Comment by wb14123** [comment]
Sorry. I thought you are commented on the other issue...  I'm not working on this for now. Because it is just a side project and I have no good way to implement it easily.

**Comment by crownedgrouse** [comment]
Closing this old stuff
